Repository AY2425S1-CS2103T-W08-3/tp, pull requests merged in 2024-11, with the labels that each got.

#153 Standardize Message Usage String for all commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
Labels: alpha-bug

#156 Fix invalid level reassignment for students
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
Labels: alpha-bug

#169 Move subject validation from AddCommandParser to AddCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: severity.Low

#170 Fix bugs for Find Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: alpha-bug

#173 Ensure CommandParser uses student field parsers.
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: alpha-bug

#176 Tag command clear subject when level is none none
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
Labels: alpha-bug

#174 Update UI Display
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/Ui.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
Labels: type.Bug, priority.High, alpha-bug

#177 Edit error logic for view, tag and note commands
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Bug, priority.High, alpha-bug

#181 Fix messages for task index and index
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UpdateTaskCommandParserTest.java
Labels: alpha-bug

#186 Fix table of contents
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: alpha-bug

#185 Update testing instructions and design considerations
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: alpha-bug

#189 Add more diagrams to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram-Logic.puml
  docs/diagrams/TagSequenceDiagram-Logic.puml
Labels: alpha-bug

#195 Add UI activity diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiActivityDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
Labels: alpha-bug

#196 Bug Fixes for UpdateTask and Update Commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/model/student/Subject.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/model/student/SubjectTest.java
Labels: alpha-bug

#209 Fix bugs with UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/site.json
Labels: type.Bug, priority.High

#263 Prevent UI from showing "NONE NONE" as level
  src/main/java/seedu/address/model/student/Level.java
  src/main/java/seedu/address/model/student/Subject.java
  src/main/java/seedu/address/model/student/predicate/LevelContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/DetailsDisplay.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: type.Bug, priority.High

#272 Fix UG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/view_student.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/student/task/TaskDeadline.java
Labels: type.Bug, priority.High

#275 Fix links in command table and formatting
  docs/UserGuide.md
Labels: type.DocumentationBug
