Repository AY2425S1-CS2103T-W08-3/tp, pull requests merged in 2024-10, with the labels that each got.

#36 Add NFRs and Glossary in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#37 Update DG: target user, value prop, user stories
  docs/DeveloperGuide.md
Labels: priority.High

#39 Add Note and emergency contact field Remove Email field
  src/main/java/seedu/address/commons/util/EnumUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Level.java
  src/main/java/seedu/address/model/tag/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/EnumUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#47 Edit fields Subject, Level, Tag
  config/checkstyle/checkstyle.xml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSubject.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SubjectTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#48 Add Record Notes Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.High

#49 Add ability to tag students by subject and level
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#50 Update add and update commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdatePersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/LevelTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/UpdatePersonDescriptorBuilder.java
Labels: type.Epic, priority.High

#51 Update find student command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicate/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/LevelContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicate/SubjectContainsKeywordsPredicate.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicate/LevelContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicate/SubjectContainsKeywordsPredicateTest.java
Labels: type.Epic, priority.High

#58 Branch task field
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/person/task/Task.java
  src/main/java/seedu/address/model/person/task/TaskDeadline.java
  src/main/java/seedu/address/model/person/task/TaskDescription.java
  src/main/java/seedu/address/model/person/task/TaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdatePersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/task/TaskDeadlineTest.java
  src/test/java/seedu/address/model/person/task/TaskDescriptionTest.java
  src/test/java/seedu/address/model/person/task/TaskListTest.java
  src/test/java/seedu/address/model/person/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#61 Add test coverage for TagCommand and its Parser
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: priority.High

#60 Add tasks to student
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/task/TaskList.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
Labels: type.Story, priority.High

#63 Add Delete Tasks Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/task/TaskList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#65 Fix success message of Note Command
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
Labels: type.Bug

#69 Bug fix name and parseName
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, severity.Low

#83 Update UG again
  docs/UserGuide.md
Labels: type.Task

#80 Add update task command
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java
  src/main/java/seedu/address/model/person/task/TaskList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateTaskCommandParserTest.java
  src/test/java/seedu/address/model/person/task/TaskListTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/UpdateTaskDescriptorBuilder.java
Labels: type.Story, priority.High

#89 Add Lesson Time field for Person
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/LessonTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLessonTime.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdatePersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/model/person/LessonTimeTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/UpdatePersonDescriptorBuilder.java
Labels: priority.High

#92 Update AddTaskCommand, DeleteTaskCommand
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
Labels: type.Bug, severity.Medium, priority.High

#100 Update StorageClassDiagram
  docs/diagrams/StorageClassDiagram.puml
Labels: severity.Low, priority.High

#102 Fix UI bug and update links in UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/LevelTest.java
  src/test/java/seedu/address/model/person/SubjectTest.java
  src/test/java/seedu/address/model/person/predicate/LevelContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.High

#99 Edit Model and Better Model UML class diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#105 Implement UI for lesson time
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/ui/DetailsDisplay.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailsDisplay.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#101 Add Tag Sequence Diagram
  docs/diagrams/TagSequenceDiagram-Logic.puml
  docs/diagrams/TagSequenceDiagram-Model.puml
Labels: type.Task, priority.High

#109 Branch fix coding standard for parsers
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: severity.Low, priority.Medium

#119 Change Person fields to be Case insensitive and ignore different spacing.
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/LessonTime.java
  src/main/java/seedu/address/model/person/Level.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Subject.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/LessonTimeTest.java
  src/test/java/seedu/address/model/person/LevelTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SubjectTest.java
Labels: type.Task, alpha-bug

#122 Update DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, alpha-bug

#142 Update links and edit diagram size
  docs/DeveloperGuide.md
Labels: alpha-bug

#134 Bug fixes for addtask
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/model/student/task/TaskDeadline.java
  src/main/java/seedu/address/model/student/task/TaskDescription.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/model/student/NoteTest.java
  src/test/java/seedu/address/model/student/task/TaskDeadlineTest.java
  src/test/java/seedu/address/model/student/task/TaskDescriptionTest.java
Labels: type.Bug, priority.High, alpha-bug

#146 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Address.java
  src/main/java/seedu/address/model/student/LessonTime.java
  src/main/java/seedu/address/model/student/Level.java
  src/main/java/seedu/address/model/student/task/TaskDeadline.java
  src/main/java/seedu/address/model/student/task/TaskDescription.java
Labels: type.Bug, priority.High, alpha-bug
